import React from "react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="bg-white py-16">
          <div className="container mx-auto px-6 text-center">
            <h1 className="text-4xl font-bold text-gray-800 mb-2">
              Scriptorium
            </h1>
            {/* <p className="text-xl text-gray-600 mb-6">
              Discover everything you need in one place.
            </p> */}
            <Link href="/login">
              {/* <a> */}
                <button className="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 transition duration-300">
                  Login
                </button>
              {/* </a> */}
            </Link>
          </div>
        </section>
      </main>
    </>
  );
}
